### PR TITLE
New facebook sdk

### PR DESCRIPTION
**Pull request by MariusVolkhart**
@nockertsb please review

### CODE REVIEW

**Comment by nockertsb** [comment]
@MariusVolkhart 
2 things I noticed while testing out the changes:
* On the login screen the Facebook button is now smaller than the Twitter one
* After I log in with Facebook the `VendorTrucksService` gets a 401 response that causes a `SocialCredentialsException` to be thrown

For the 401 error, I'm not sure If that's because I don't have any trucks set up on my account or what the deal is, but the app crashes as soon as I log in.

**Comment by MariusVolkhart** [comment]
I think i have a crash report for the login (though it was from me, not you)

The button I noticed too. Specifying a fixed height didn't fix it so i moved on. I'd recommend coming back to it, but could do it before merging if you prefer.

**Comment by MariusVolkhart** [comment]
@nockertsb Fixed the fb button. The 401 error is not something i've seen (and turns out i don't have a crash log). There's a few fixes to auth logic in the next PR though.

**Comment by nockertsb** [comment]
Button looks good. I'm not seeing that 401 anymore and since you didn't run into it at all we can call it good.

**Pull request merged**
