### PR TITLE
Ability to deep link to trucks

### PR DESCRIPTION
**Pull request by MariusVolkhart**
@nockertsb please review

There is a `FIXME` that I left in because I want to fix it after some of the other things have been merged

### CODE REVIEW

**Comment by MariusVolkhart** [comment]
Also worth noting that the URLs are incorrect. They haven't been defined yet by macon, but they'll be easy to change

**Comment by nockertsb** [comment]
@MariusVolkhart Do you want to wait until the FIXME is resolved before merging this?

**Comment by MariusVolkhart** [comment]
Yeah i'll fix it

**Comment by MariusVolkhart** [comment]
@nockertsb fixed. thanks

**Comment by nockertsb** [comment]
ship it

**Comment by nockertsb** [comment]
:shipit:

**Pull request merged**
